server {
    listen 8000;
    root /usr/share/nginx/html;
    index index.html;

    # SPA (vue-router em history mode)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # repassa /api para o backend
    location /api/ {
        proxy_pass http://backend:5678/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}